### ISSUE TITLE
save data to CSV file

### ISSUE THREAD

**Issue by machine85** [JerBouma/FundamentalsQuantifier#1]
Hello,
thank you for this great package,

after doing this:

financial_ratios_annually = fa.financial_ratios(ticker, api_key, period="annual")

how can i save the data to CSV file ?
what is the type of the data ?

regards,
Tom

**Comment by JerBouma** [comment]
I believe you made this issue in the wrong repository. However to answer your questions:

All data is placed in a DataFrame. You can send to csv or xlsx by adding `financial_ratios_annually.to_csv("name.csv")`  or by addng `financial_ratios_annually.to_excel("name.xlsx")`. Please for more info on the function type `help(fa.financial_ratios)` and for DataFrame info type `help(pd.DataFrame)`.

**Comment by machine85** [comment]
thank you Sir
